# -*- coding: utf-8 -*-
"""GAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJC4varsXxDEStNIjMwsBADtJ9W6KT_2
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense, LeakyReLU, BatchNormalization
from tensorflow.keras.models import Sequential
import matplotlib.pyplot as plt

# Hyperparameters
latent_dim = 100
epochs = 5000
batch_size = 64

# Generate real data (random numbers between -1 and 1)
def generate_real_data(samples=1000):
    return np.random.uniform(-1, 1, (samples, 1))

# Build Generator
def build_generator():
    model = Sequential([
        Dense(16, input_dim=latent_dim),
        LeakyReLU(alpha=0.2),
        BatchNormalization(),
        Dense(32),
        LeakyReLU(alpha=0.2),
        Dense(1, activation='tanh')
    ])
    return model

# Build Discriminator
def build_discriminator():
    model = Sequential([
        Dense(32, input_dim=1),
        LeakyReLU(alpha=0.2),
        Dense(16),
        LeakyReLU(alpha=0.2),
        Dense(1, activation='sigmoid')
    ])
    model.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.Adam(), metrics=['accuracy'])
    return model

# Create Models
generator = build_generator()
discriminator = build_discriminator()

discriminator.trainable = False  # Freeze Discriminator when training GAN

# Build GAN
gan = Sequential([generator, discriminator])
gan.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.Adam())

# Training GAN
def train_gan(epochs=10000, batch_size=64):
    for epoch in range(epochs):
        # Train Discriminator
        real_data = generate_real_data(batch_size)
        fake_data = generator.predict(np.random.randn(batch_size, latent_dim))

        real_labels = np.ones((batch_size, 1))
        fake_labels = np.zeros((batch_size, 1))

        d_loss_real = discriminator.train_on_batch(real_data, real_labels)
        d_loss_fake = discriminator.train_on_batch(fake_data, fake_labels)

        # Train Generator
        noise = np.random.randn(batch_size, latent_dim)
        misleading_labels = np.ones((batch_size, 1))  # Trick discriminator
        g_loss = gan.train_on_batch(noise, misleading_labels)

        # Print progress every 1000 epochs
        if epoch % 1000 == 0:
            print(f"Epoch {epoch}: D Loss = {d_loss_real[0] + d_loss_fake[0]}, G Loss = {g_loss}")

# Train the GAN
train_gan(epochs, batch_size)

# Generate samples and plot
noise = np.random.randn(100, latent_dim)
fake_samples = generator.predict(noise)
plt.hist(fake_samples, bins=20, alpha=0.7, label='Generated Data')
plt.legend()
plt.show()