# -*- coding: utf-8 -*-
"""picture to csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKizRyDBnoMzJsEApXOSwz_xJ54QfzYe
"""



!pip install pytesseract

!apt update
!apt install -y tesseract-ocr

from PIL import Image
import pytesseract

# Load the image
image_path = "/content/new.jpg"
image = Image.open(image_path)

# Perform OCR
text = pytesseract.image_to_string(image)

# Print or save the text
print(text)

# If the table needs to be structured, you'll need additional processing.

from PIL import Image
import pytesseract
import pandas as pd

# Load the image
image_path = "/content/new.jpg"
image = Image.open(image_path)

# Perform OCR to extract text
text = pytesseract.image_to_string(image)

# Optionally, display the extracted text to verify
print(text)

# You can process the text into a structured format if it is tabular
# Example: If the text is in a table-like format, split it into rows and columns
# For simplicity, let's assume the columns are separated by spaces or tabs

# Split the text into rows
rows = text.split("\n")

# Process rows into a list of lists (e.g., by splitting columns)
data = [row.split() for row in rows if row.strip()]

# Convert to DataFrame (optional, but useful for CSV export)
df = pd.DataFrame(data)

# Export the DataFrame to CSV
df.to_csv("output.csv", index=False)

print("CSV file has been saved as output.csv")